version: '3'

services:
  proxy_server:
    build:
      context: .
      dockerfile: proxy_server.dockerfile
    ports:
      - "2000:2000/udp"
    depends_on:
      - avro_serializer
      - json_serializer
      - mpack_serializer
      - naive_serializer
      - pbuffer_serializer
      - xml_serializer
      - yaml_serializer
    environment:
      AVRO_PORT: "2001"
      AVRO_NAME: "avro_serializer"
      JSON_PORT: "2002"
      JSON_NAME: "json_serializer"
      MPACK_PORT: "2003"
      MPACK_NAME: "mpack_serializer"
      NAIVE_PORT: "2004"
      NAIVE_NAME: "naive_serializer"
      PBUFFER_PORT: "2005"
      PBUFFER_NAME: "pbuffer_serializer"
      XML_PORT: "2006"
      XML_NAME: "xml_serializer"
      YAML_PORT: "2007"
      YAML_NAME: "yaml_serializer"

  avro_serializer:
    build:
      context: .
      dockerfile: ./avro.dockerfile
    ports:
      - "2001:2001/udp"
    environment:
      SERVER_NAME: "avro_serializer"
      SERVER_PORT: "2001"

  json_serializer:
    build:
      context: .
      dockerfile: ./json.dockerfile
    ports:
      - "2002:2002/udp"
    environment:
      SERVER_NAME: "json_serializer"
      SERVER_PORT: "2002"

  mpack_serializer:
    build:
      context: .
      dockerfile: ./mpack.dockerfile
    ports:
      - "2003:2003/udp"
    environment:
      SERVER_NAME: "mpack_serializer"
      SERVER_PORT: "2003"

  naive_serializer:
    build:
      context: .
      dockerfile: ./naive.dockerfile
    ports:
      - "2004:2004/udp"
    environment:
      SERVER_NAME: "naive_serializer"
      SERVER_PORT: "2004"

  pbuffer_serializer:
    build:
      context: .
      dockerfile: ./pbuffer.dockerfile
    ports:
      - "2005:2005/udp"
    environment:
      SERVER_NAME: "pbuffer_serializer"
      SERVER_PORT: "2005"

  xml_serializer:
    build:
      context: .
      dockerfile: ./xml.dockerfile
    ports:
      - "2006:2006/udp"
    environment:
      SERVER_NAME: "xml_serializer"
      SERVER_PORT: "2006"

  yaml_serializer:
    build:
      context: .
      dockerfile: ./yaml.dockerfile
    ports:
      - "2007:2007/udp"
    environment:
      SERVER_NAME: "yaml_serializer"
      SERVER_PORT: "2007"