# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test_data.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftest_data.proto\"\xa4\x01\n\x0fMonaLizaPicture\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x06\x62uyers\x18\x04 \x03(\x0b\x32\x1c.MonaLizaPicture.BuyersEntry\x12\x0c\n\x04year\x18\x05 \x01(\x05\x12\x0c\n\x04size\x18\x06 \x01(\x02\x1a-\n\x0b\x42uyersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_data_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MONALIZAPICTURE_BUYERSENTRY._options = None
  _MONALIZAPICTURE_BUYERSENTRY._serialized_options = b'8\001'
  _MONALIZAPICTURE._serialized_start=20
  _MONALIZAPICTURE._serialized_end=184
  _MONALIZAPICTURE_BUYERSENTRY._serialized_start=139
  _MONALIZAPICTURE_BUYERSENTRY._serialized_end=184
# @@protoc_insertion_point(module_scope)
